### PR TITLE
feat: make flakes a compile-time build option

### LINKED ISSUE #1: Flake - compile option
I wonder whether it's feasible, to avoid the `--flake` mistake of the past.

Let's face it: you either are sold (and use flakes everywhere [you can]) or you aren't and don't touch them [if you can].

So instead, would it be possible to simply have two compile options of `nixos`? One with and one without flake? -- and avoid unhandy flags.

### PR DESCRIPTION
**Pull request by water-sucks**
Flakes are a pretty invasive feature: since people either use them or don't, it is likely better to make two separate versions of the package, one which lets users use flakes more ergonomically, and one that allows for legacy-style users to continue using legacy-style switching with either the NIXOS_CONFIG variable or NIX_PATH's `nixos-config:` property being set to the location of `configuration.nix`.

This compile-time option can see use in other places that have the potential to use flakes, such as `nixos init`.

Closes #1.

### CODE REVIEW

**Comment by blaggacao** [comment]
Really cool! &mdash; I also like how straight forward the change is.

I think, inadvertently, we now hit the next design question. What do do with `nixos init` in a flake compile?
```
❯ ./result/bin/nixos init --help
Initialize a NixOS configuration template.

Usage:
    nixos init [options]

Options:
    -d, --dir <NAME>              Directory to write configuration to
    -f, --force                   Force generation of configuration.nix
    -n, --no-fs                   Do not generate `fileSystem` option configuration
    -r, --root <DIR>              Treat the given directory as the root directory
    -s, --show-hardware-config    Print hardware config to stdout and exit
```

It's not a trivial question, but an important one, since there are so many "frameworks" to set up your local  / server nixos flake environment.

Maybe we may start with an equivalent to `configuration.nix` in a trivial enough `flake.nix`...

An outlook would be that "frameworks" could implement their plugins to enable more advanced / custom templates. That begs another question: should plugins be able to overload / hook into commands?

But for now, maybe just a  minimal `./flake.nix` + `./configuration.nix` should be fine.

**Comment by water-sucks** [comment]
Yeah, I was thinking about that. At first, I was thinking about using a template like this:

```nix
{
  description = "A basic NixOS configuration";

  inputs = {
    nixpkgs.url = "github.com:nixos/nixpkgs/nixos-unstable";
  };

  output = {nixpkgs, ...}: {
    nixosConfigurations.hostname = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
      ];
    };
  };
}
```

and using the same `configuration.nix` template from the legacy configuration. Is this a satisfactory way to go?

`hostname` should probably be filled in with a better default, any thoughts on what that could be? The `system` would also be filled in by whatever `nixpkgs.hostSystem` is set to later on in the `hardware-configuration.nix`, so that's not an issue.

I'm thinking I should use some other branch for the nixpkgs version, not nixos-unstable, but that's probably going to have to be controlled by another compile-time build variable like `nixpkgs_version` or something like that where the derivation can fill it in, and `nixos-unstable` can be used as a default instead. That's a little annoying, but it can be done.

**Comment by blaggacao** [comment]
> Is this a satisfactory way to go? [Reuse `configuration.nix`]

Absolutely. Others, among them myself, can then chime in and iterate.

> any thoughts on what that could be?

`my-nixos` seems like a good placeholder value.

> The system would also be filled in by whatever [later]

I'd have to check, iirc, this ain't even necessary any more. If it still is, that's probably a remaining design issue in the upstream implementation.

> compile-time build variable like nixpkgs_version

That's a good idea. I wouldn't default to unstable, but to the current latest release, in order to communicate some expectations and not have people go down the rabbit hole of chasing the latest and greatest, by default.

**Comment by water-sucks** [comment]
Alright @blaggacao I think this is good to merge.

**Pull request merged**
